### ISSUE TITLE
content-restructuring: recommended

### ISSUE THREAD

**Issue by vlle1** [vlle1/iprog#6]
Suggestions from me: On "Recommended" show more stuff per activity, not just the title. 

Also, once "Add" is pressed, disable the button or show a checkbox or sth!

**Comment by Olme786** [comment]
I think i will make something to fix the problem with the detailsView I will try to show  the name of the activity in a rectangle and show the remain information in another rectangle that it can be stick with the previous one or make a dropdown button that shows the information.

**Comment by Olme786** [comment]
Gabriel, I leave you the work of the buttons

**Comment by gdalborg** [comment]
Add button is working now. The text changes to "Added" and disables are click

**Comment by gdalborg** [comment]
I will have a look at the DetailsView and try to make it more convenient. For example, seeing Accessability on a scale from 0 to 1 is not good. Instead we could write Accessability as Easy, Medium or Tricky. What do you think?

**Comment by vlle1** [comment]
On "Recommended" show more stuff per activity! On the "recommended" view you should see the information directly (how many people, cost, etc.)

**Comment by vlle1** [comment]
we added the content to recommended, doesn't look nice, maybe also include the icons for participants as in detailsView!
Styling left to do!
