### ISSUE TITLE
Improve / redesign Detailsview

### ISSUE THREAD

**Issue by vlle1** [vlle1/iprog#7]
from my point of view, it is currently a bit counterintuitive: "recommended" has more features per activity than details view! The details should ....

either: only accessible from saved activities, 
or: add an "add" button when coming from "recommended".

**Comment by Olme786** [comment]
I think it is neccesary to access the details from both views, however if you consider that only needs to be seeing in savedActivities i changed that and the style to make clear that it is only accessible from one View

**Comment by Olme786** [comment]
I made that details only can be accessed from savedActivities.
